name: Deploy To Fargate

on:
  push:
    branches: [ kirin_development ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2