name: Deploy To Fargate

on:
  push:
    branches: [ prod ]

env:
  REGION: ap-southeast-1

jobs:
  deploy:
    name: Deploy
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}
          role-duration-seconds: 1800
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push nginx image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.amazon-ecr-login.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}-nginx
          IMAGE_TAG: ${{ steps.vars.outputs.tag }}
          DOCKER_BUILDKIT: 1
        # run: |
        #   docker build \
        #     --cache-from=$ECR_REGISTRY/$ECR_REPOSITORY:latest --build-arg BUILDKIT_INLINE_CACHE=1 . \
        #     -f ./docker/nginx/Dockerfile \
        #     -t $ECR_REGISTRY/$ECR_REPOSITORY:latest \
        #     -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        #   docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        #   docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        run: |
          echo $ECR_REGISTRY/$ECR_REPOSITORY:latest